version: "3"

services:
  app:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.server.production
      args:
        NODE_ENV: production
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "49100:8080"
    environment:
      - LOG_LEVEL=debug
      - API_ENDPOINT=$API_ENDPOINT
      - CLIENT_ENDPOINT=$CLIENT_ENDPOINT
      # OFFLINE_DEV_ID: true

  mongo:
    image: mongo:6
    # logging:
    #   driver: none
    volumes:
      - ./db_data:/data/db
    ports:
      - "27017:27017"

  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.client.production
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_ENDPOINT=$API_ENDPOINT
